all:
	gcc -o password_manager_test password_manager_test.c ../../lib/header/password_manager.h ../../lib/source/password_manager.c ../../lib/header/list.h ../../lib/source/list.c ../../lib/header/debug.h ../../lib/header/memory.h ../../lib/source/memory.c -lm -g3
clean:
	rm password_manager_test